pref("extensions.dragscroll-version", "0.0.0");
pref("extensions.dragscroll.on", true);
pref("extensions.dragscroll.grabCursor", "url(chrome://dragscroll/skin/grab.png) 10 4, move");
pref("extensions.dragscroll.grabbingCursor", "url(chrome://dragscroll/skin/grabbing.png) 10 4, move");
pref("extensions.dragscroll.togKey", 68);
pref("extensions.dragscroll.useCtrl", false);
pref("extensions.dragscroll.useAlt", true);
pref("extensions.dragscroll.useShift", true);
pref("extensions.dragscroll.dragInc", "1");
pref("extensions.dragscroll.mult", "1");
pref("extensions.dragscroll.sbmode", false);
pref("extensions.dragscroll.samecur", false);
pref("extensions.dragscroll.reverse", false);
pref("extensions.dragscroll.flickon", true);
pref("extensions.dragscroll.flickspeed_ppms", "2");
pref("extensions.dragscroll.flicktimelimit", "150");
pref("extensions.dragscroll.flickwhole", 0);
pref("extensions.dragscroll.momOn", true);
pref("extensions.dragscroll.momExtent", "500");
pref("extensions.dragscroll.momVariation", "0.5");
pref("extensions.dragscroll.momFriction", "0");
pref("extensions.dragscroll.smoothStop", true);
pref("extensions.dragscroll.button", 0);
pref("extensions.dragscroll.qtOn", true);
pref("extensions.dragscroll.qtOnCnt", 2);
pref("extensions.dragscroll.qtOnTime", "400");
pref("extensions.dragscroll.qtOffCnt", 1);
pref("extensions.dragscroll.qtOffTime", "150");
pref("extensions.dragscroll.qtOffCopy", false);
pref("extensions.dragscroll.strict", false);
pref("extensions.dragscroll.toolsMenuEntry", true);
pref("extensions.dragscroll.shortdT",50);
pref("extensions.dragscroll.shortdX",2);
pref("extensions.dragscroll.flickhoriz", 0);
pref("extensions.dragscroll.blacklist","[]");
pref("extensions.dragscroll.specialBL","embed|object|applet");
pref("extensions.dragscroll.hiddenBL0",'[{"id":"gcalendar","on":"true","url":"google.com/calendar","elem":"*"},{"id":"gdocs","on":"true","url":"docs.google.com","elem":"*"},{"id":"links","on":"true","url":"*","elem":"*:link,*:visited,*[role=\\"link\\"]"},{"id":"maps","on":"true","url":"*","elem":"div[id*=\\"map\\"],div[class*=\\"map\\"],div[id*=\\"Map\\"],div[class*=\\"Map\\"]"},{"id":"textfields","on":"true","url":"*","elem":"input:not([type=\\"button\\"]):not([type=\\"checkbox\\"]):not([type=\\"image\\"]):not([type=\\"radio\\"]):not([type=\\"reset\\"]):not([type=\\"submit\\"]),textarea,*[role=\\"textbox\\"]"},{"id":"menus","on":"true","url":"*","elem":"select,*[role*=\\"menu\\"],*[role=\\"option\\"],div[class*=\\"goog\\"][class*=\\"menu\\"],*[role=\\"listbox\\"]"},{"id":"buttons","on":"true","url":"*","elem":"button,input[type=\\"button\\"],input[type=\\"file\\"],input[type=\\"image\\"],input[type=\\"reset\\"],input[type=\\"submit\\"],*[role*=\\"button\\"],div[class*=\\"goog\\"][class*=\\"button\\"]"},{"id":"mediacontrols","on":"true","url":"*","elem":"video,div.ovp-controls,div.sv-controls,div.jp-interface,div.mejs-controls,div.ui-video-control,div.media-controls,div.vjs-controls,div.oipcontrols,div.hvideo,div.h5_lb_controls"},{"id":"disableds","on":"true","url":"*","elem":"*[disableGrabAndDrag=\\"true\\"]"},{"id":"editable","on":"true","url":"*","elem":"*[contenteditable=\\"true\\"]"},{"id":"sliders","on":"true","url":"*","elem":"*[role=\\"slider\\"],*[role=\\"scrollbar\\"],*[class*=\\"slider\\"],*.scroll,*.jspDrag"},{"id":"draggables","on":"true","url":"*","elem":"*[draggable=\\"true\\"],*[class*=\\"draggable\\"],*[class*=\\"handle \\"],*[class$=\\"handle\\"],*.x-unselectable,:not(table)[class*=\\"sortable\\"]"},{"id":"canvas","on":"true","url":"*","elem":"canvas"},{"id":"addons","on":"true","url":"*","elem":"#pxa-area-protector"},{"id":"checkboxes","on":"false","url":"*","elem":"input[type=\\"checkbox\\"],*[role=\\"checkbox\\"]"},{"id":"radiobuttons","on":"false","url":"*","elem":"input[type=\\"radio\\"],*[role*=\\"radio\\"]"}]');
pref("extensions.dragscroll.hiddenBL1",'[{"id":"disableds","on":"true","url":"*","elem":"*[disableGrabAndDrag=\\"true\\"]"},{"id":"links","on":"false","url":"*","elem":"*:link,*:visited,*[role=\\"link\\"]"}]');
pref("extensions.dragscroll.hiddenBL2",'[{"id":"disableds","on":"true","url":"*","elem":"*[disableGrabAndDrag=\\"true\\"]"},{"id":"links","on":"false","url":"*","elem":"*:link,*:visited,*[role=\\"link\\"]"}]');
pref("extensions.dragscroll.textdoesntcount",'[{"on":"true","url":"*","elem":"*:link,*:visited,*[role=\\"link\\"]"}]');
pref("extensions.dragscroll.countsastext",'[{"on":"true","url":"*","elem":"input:not([type=\\"button\\"]):not([type=\\"checkbox\\"]):not([type=\\"image\\"]):not([type=\\"radio\\"]):not([type=\\"reset\\"]):not([type=\\"submit\\"]),textarea,*[role=\\"textbox\\"]"}]');
pref("extensions.dragscroll@honoredsoft.com.description", "chrome://dragscroll/locale/dragscroll.properties");
